### ISSUE TITLE
Running simulation

### ISSUE THREAD

**Issue by octopusann** [waternumbers/dynatop#16]
Running on Rstudio running R 3.6.0 on Scientific Linux 7

Line 123 of simulate_model hangs up. I left it over the weekend and it still hadn't run. It seems  to be trying to Reprofile. Had to resort to switching off and rebooting to get out of it.

Reran today JUST the simulation line nothing after an hour.

No error messages to report.

**Comment by octopusann** [comment]
Tried changing the Initial_recharge value but that didn't help.

**Comment by waternumbers** [comment]
Please attach script (or copy section) so I know exactly what the command is

**Comment by octopusann** [comment]
I thought that’s what I’d done. It’s just not letting me install either dynatopGIS or dynatop under Windows.

Dr. Ann Kretzschmar
Senior Research Associate Q-NFM

B505 LEC 1

Lancaster Environment Centre
Lancaster University
LA1 4YQ

**Comment by waternumbers** [comment]
Can't see an attachment on this - think your comment above is about a different issue.

**Comment by octopusann** [comment]
Just hung the machine up trying to get you a screenshot!  I think may have spotted the problem though - possibly. The parameters are all still set to default! Will check it out once the machine unlocks. Might have to crash it out and start again.


Dr. Ann Kretzschmar



Lancaster Environment Centre

Lancaster University

LA1 4YQ



kretzsch@exchange.lancs.ac.uk<mailto:kretzsch@exchange.lancs.ac.uk>

octopusann@me.com<mailto:octopusann@me.com>

mobile: 07775-968315



________________________________

**Comment by octopusann** [comment]
initial_recharge <- as.numeric(obs[1,"discharge_xts"])*3600/sum(model$hillslope$area)

## start logging to see look at performance
Rprof("Simulation_perf_kent_4.out")
## simulate the model - not very quick...
hillslope_out <- dynatop(model,in_obs[1:1000,],initial_recharge)
Rprof(NULL)

its a section from your sample script. When I run it, it just sits and looks at me! 
This is the model (assuming the screenshot worked!)
![Screenshot from 2019-10-17 13-38-51](https://user-images.githubusercontent.com/13494102/67009465-99cb7100-f0e3-11e9-8647-9ccad3e59720.png)

**Comment by octopusann** [comment]
OK had lunch and I see now that the parameters do have values!  screenshot of model sent.


Dr. Ann Kretzschmar



Lancaster Environment Centre

Lancaster University

LA1 4YQ



kretzsch@exchange.lancs.ac.uk<mailto:kretzsch@exchange.lancs.ac.uk>

octopusann@me.com<mailto:octopusann@me.com>

mobile: 07775-968315



________________________________

**Comment by waternumbers** [comment]
Assuming this is the Kent example it sits and looks at me for about 24hr as well (I removed the printing of time steps). If you want to see if it is running see if the file Simulation_perf_kent_4.out is growing in size.

**Comment by octopusann** [comment]
It is. Did you actually get any results?  Where does the perf file get written to?


Dr. Ann Kretzschmar



Lancaster Environment Centre

Lancaster University

LA1 4YQ



kretzsch@exchange.lancs.ac.uk<mailto:kretzsch@exchange.lancs.ac.uk>

octopusann@me.com<mailto:octopusann@me.com>

mobile: 07775-968315



________________________________

**Comment by waternumbers** [comment]
Yes but not rerun with the corrected rainfall. Doesn't generate a file of performance (if that is what you mean). The file generated by Rprof() is for profiling purposes. 

Closing this issue since the model is in fact running. If you find it appears to stop (inc the log file not growing) then please reopen.

**Comment by octopusann** [comment]
Sorry confused. What log file?


Dr. Ann Kretzschmar



Lancaster Environment Centre

Lancaster University

LA1 4YQ



kretzsch@exchange.lancs.ac.uk<mailto:kretzsch@exchange.lancs.ac.uk>

octopusann@me.com<mailto:octopusann@me.com>

mobile: 07775-968315



________________________________
