### ISSUE TITLE
Sware Gill outputs

### ISSUE THREAD

**Issue by octopusann** [waternumbers/dynatop#19]
The model has now run with routing for Sware Gill and has produced output (Graph attached) but I'm not sure how to interpret it. Are these expected results? There doesn't seem to be any difference between hillslope_out and channel_out when plotted. Is this because its a small catchment with only one reach?

![Screenshot from 2019-10-25 14-25-42](https://user-images.githubusercontent.com/13494102/67575111-bdba3280-f733-11e9-8272-a8dc1892507e.png)

**Comment by octopusann** [comment]
Ok moving on!  The PET was far to o high - now set to zero for now so we have a hydrograph! Uncalibrated but a huge step forward.
![Screenshot from 2019-10-25 17-03-32](https://user-images.githubusercontent.com/13494102/67586437-88b8da80-f749-11e9-882b-43e0374f1bcd.png)

**Comment by waternumbers** [comment]
This issue appears to be stale. If you want further input please open a new issue.
